substitutions:
  _IMAGE_NAME: gcr.io/linear-pointer-457514-g1/mi-app
  _SERVICE_NAME: mi-app
  _REGION: us-central1

steps:
  # Paso 1: Compilar la app con Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: '.'

  # Paso 2: Construir imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}', '.']

  # Paso 3: Subir imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

  # Paso 4: Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_IMAGE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - managed
      - '--allow-unauthenticated'

images:
  - '${_IMAGE_NAME}'



options:
  logging: CLOUD_LOGGING_ONLY