steps:
  - name: 'maven:3.9-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_IMAGE_NAME}',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image=${_IMAGE_NAME} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --quiet
